#!/usr/bin/env python3
"""Repair broken internal geometry references in an Inreal USD export.

The MuJoCo-to-USD export used for Inreal V2 can leave each rigid body's
``visuals`` and ``collisions`` prim referencing an empty
``/Flattened_Prototype_*`` prim.  The actual source geometry is still present
under the asset's hidden top-level ``visuals`` and ``collisions`` libraries.
This tool reconnects every rigid body to its matching source geometry and
removes collision-group prims unsupported by IsaacLab's physics replication.
"""

from __future__ import annotations

import argparse
import os
from pathlib import Path

from pxr import Usd, UsdPhysics


def repair_usd(input_path: Path, output_path: Path) -> None:
    """Repair *input_path* and atomically write the result to *output_path*."""
    stage = Usd.Stage.Open(str(input_path))
    if stage is None:
        raise RuntimeError(f"Unable to open USD: {input_path}")

    asset_root = stage.GetDefaultPrim()
    if not asset_root:
        raise RuntimeError(f"USD has no default prim: {input_path}")

    body_container = asset_root.GetChild("pelvis")
    source_visuals = asset_root.GetChild("visuals")
    source_collisions = asset_root.GetChild("collisions")
    if not body_container or not source_visuals or not source_collisions:
        raise RuntimeError("Expected pelvis, visuals, and collisions below the default prim")

    repaired = 0
    for body in body_container.GetChildren():
        if not body.HasAPI(UsdPhysics.RigidBodyAPI):
            continue

        for library_name, source_library in (
            ("visuals", source_visuals),
            ("collisions", source_collisions),
        ):
            target = body.GetChild(library_name)
            source = source_library.GetChild(body.GetName())
            if not target or not source:
                raise RuntimeError(
                    f"Missing {library_name} mapping for rigid body {body.GetPath()}"
                )

            references = target.GetReferences()
            references.ClearReferences()
            if not references.AddInternalReference(source.GetPath()):
                raise RuntimeError(f"Failed to reference {source.GetPath()} from {target.GetPath()}")
            target.SetInstanceable(True)
            repaired += 1

    collision_groups = [
        prim.GetPath() for prim in stage.Traverse() if prim.IsA(UsdPhysics.CollisionGroup)
    ]
    for prim_path in collision_groups:
        stage.RemovePrim(prim_path)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    temporary_path = output_path.with_name(f".{output_path.name}.tmp")
    if not stage.GetRootLayer().Export(str(temporary_path)):
        raise RuntimeError(f"Failed to export repaired USD to {temporary_path}")
    os.replace(temporary_path, output_path)

    print(
        f"Repaired {repaired} geometry references across {repaired // 2} rigid bodies; "
        f"removed {len(collision_groups)} collision groups; wrote {output_path}"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input", type=Path, help="Source USD generated by the converter")
    parser.add_argument("output", type=Path, help="Repaired IsaacLab USD")
    args = parser.parse_args()
    repair_usd(args.input.resolve(), args.output.resolve())


if __name__ == "__main__":
    main()
